export const MOCK_ALERTS = [
  {
    id: 'mock-alert-1',
    severity: 'Extreme',
    event: 'Severe Thunderstorm & Flash Flood',
    headline: 'IMD RED ALERT: Severe Thunderstorm & Flash Floods approaching Pune',
    description: 'A very severe thunderstorm is expected to hit the area with extremely heavy rainfall, frequent lightning strikes, and high chances of localized flash flooding.',
    instruction: 'Stay indoors immediately. Unplug all electronic devices. Avoid standing near tall trees, poles, or water bodies. Farmers should immediately halt outdoor activities and secure livestock.',
    status: 'ACTIVE',
    area: 'Pune, Maharashtra',
    areaCode: 'MH-PN',
    version: 1,
    issuedAt: new Date(Date.now() - 3600000).toISOString(),
    expiresAt: new Date(Date.now() + 86400000).toISOString()
  },
  {
    id: 'mock-alert-2',
    severity: 'Severe',
    event: 'Heavy Rainfall',
    headline: 'ORANGE ALERT: Heavy to Very Heavy Rainfall expected in Mumbai',
    description: 'Intense precipitation likely to cause waterlogging in low-lying areas. Visibility may drop significantly during heavy spells.',
    instruction: 'Commute only if necessary. Avoid waterlogged roads. Keep emergency kits ready.',
    status: 'ACTIVE',
    area: 'Mumbai, Maharashtra',
    areaCode: 'MH-MU',
    version: 1,
    issuedAt: new Date(Date.now() - 7200000).toISOString(),
    expiresAt: new Date(Date.now() + 43200000).toISOString()
  },
  {
    id: 'mock-alert-3',
    severity: 'Moderate',
    event: 'High Wind / Squall',
    headline: 'YELLOW ALERT: Strong gusty winds approaching coastal Ratnagiri',
    description: 'Squally weather with wind speeds reaching 45-55 kmph gusting to 65 kmph is very likely over the coastal regions.',
    instruction: 'Fishermen are advised not to venture into the sea. Secure loose objects outdoors.',
    status: 'ACTIVE',
    area: 'Ratnagiri, Maharashtra',
    areaCode: 'MH-RT',
    version: 1,
    issuedAt: new Date(Date.now() - 14400000).toISOString(),
    expiresAt: new Date(Date.now() + 86400000).toISOString()
  },
  {
    id: 'mock-alert-4',
    severity: 'Severe',
    event: 'Heat Wave',
    headline: 'ORANGE ALERT: Severe Heat Wave conditions in Nagpur',
    description: 'Maximum temperatures are very likely to exceed 45°C. High risk of heat illness with prolonged exposure.',
    instruction: 'Avoid sun exposure between 11 AM and 4 PM. Stay hydrated. Wear light-colored, loose cotton clothes.',
    status: 'ACTIVE',
    area: 'Nagpur, Maharashtra',
    areaCode: 'MH-NG',
    version: 1,
    issuedAt: new Date(Date.now() - 86400000).toISOString(),
    expiresAt: new Date(Date.now() + 172800000).toISOString()
  },
  {
    id: 'mock-alert-5',
    severity: 'Minor',
    event: 'Dense Fog',
    headline: 'YELLOW ALERT: Dense morning fog affecting visibility in Nashik',
    description: 'Visibility may drop below 200 meters during the early morning hours, disrupting traffic on highways.',
    instruction: 'Drive carefully using fog lights. Maintain a safe distance from other vehicles.',
    status: 'ACTIVE',
    area: 'Nashik, Maharashtra',
    areaCode: 'MH-NS',
    version: 1,
    issuedAt: new Date(Date.now() - 1800000).toISOString(),
    expiresAt: new Date(Date.now() + 10800000).toISOString()
  },
  {
    id: 'mock-alert-6',
    severity: 'Extreme',
    event: 'Cyclone Warning',
    headline: 'IMD RED ALERT: Cyclonic Storm approaching coastal Gujarat/Maharashtra border',
    description: 'Extremely severe cyclonic storm expected to make landfall with wind speeds up to 120 kmph, causing major damage to coastal infrastructure.',
    instruction: 'Evacuate low-lying coastal areas immediately. Move to designated cyclone shelters. Stock up on food, water, and medicines.',
    status: 'ACTIVE',
    area: 'Palghar, Maharashtra',
    areaCode: 'MH-PL',
    version: 1,
    issuedAt: new Date(Date.now() - 5400000).toISOString(),
    expiresAt: new Date(Date.now() + 259200000).toISOString()
  },
  {
    id: 'mock-alert-7',
    severity: 'Moderate',
    event: 'Thunderstorm',
    headline: 'YELLOW ALERT: Scattered thunderstorms in Aurangabad',
    description: 'Isolated thunderstorms accompanied by lightning and light showers are expected during the late afternoon.',
    instruction: 'Take safe shelter during lightning activity. Do not take shelter under trees.',
    status: 'ACTIVE',
    area: 'Aurangabad, Maharashtra',
    areaCode: 'MH-AU',
    version: 1,
    issuedAt: new Date(Date.now() - 1000000).toISOString(),
    expiresAt: new Date(Date.now() + 7200000).toISOString()
  },
  {
    id: 'mock-alert-8',
    severity: 'Severe',
    event: 'Flash Flood Risk',
    headline: 'ORANGE ALERT: High risk of localized flooding in Kolhapur',
    description: 'Continuous rainfall over the past 48 hours has raised river water levels significantly. Low-lying areas are at risk of inundation.',
    instruction: 'Move livestock to higher ground. Do not attempt to cross flooded bridges or roads.',
    status: 'ACTIVE',
    area: 'Kolhapur, Maharashtra',
    areaCode: 'MH-KO',
    version: 1,
    issuedAt: new Date(Date.now() - 43200000).toISOString(),
    expiresAt: new Date(Date.now() + 129600000).toISOString()
  },
  {
    id: 'mock-alert-9',
    severity: 'Minor',
    event: 'Light Hail',
    headline: 'YELLOW ALERT: Possibility of light hailstorms in Solapur',
    description: 'Convective clouds may cause brief spells of light hail along with gusty winds.',
    instruction: 'Protect sensitive crops using anti-hail nets if possible. Keep vehicles under cover.',
    status: 'ACTIVE',
    area: 'Solapur, Maharashtra',
    areaCode: 'MH-SO',
    version: 1,
    issuedAt: new Date(Date.now() - 3600000).toISOString(),
    expiresAt: new Date(Date.now() + 14400000).toISOString()
  },
  {
    id: 'mock-alert-10',
    severity: 'Extreme',
    event: 'Landslide Warning',
    headline: 'RED ALERT: High landslide probability in Raigad ghats',
    description: 'Incessant torrential rains have destabilized slopes. High risk of landslides blocking major highways.',
    instruction: 'Avoid traveling through ghat sections. Follow diversions issued by local traffic authorities.',
    status: 'ACTIVE',
    area: 'Raigad, Maharashtra',
    areaCode: 'MH-RG',
    version: 1,
    issuedAt: new Date(Date.now() - 7200000).toISOString(),
    expiresAt: new Date(Date.now() + 172800000).toISOString()
  },
  {
    id: 'mock-alert-11',
    severity: 'Moderate',
    event: 'Unseasonal Rain',
    headline: 'YELLOW ALERT: Unseasonal rainfall likely to affect crops in Jalgaon',
    description: 'A western disturbance is likely to cause light to moderate rainfall over the region.',
    instruction: 'Harvested crops should be stored in dry, covered places. Delay pesticide spraying.',
    status: 'ACTIVE',
    area: 'Jalgaon, Maharashtra',
    areaCode: 'MH-JL',
    version: 1,
    issuedAt: new Date(Date.now() - 86400000).toISOString(),
    expiresAt: new Date(Date.now() + 86400000).toISOString()
  },
  {
    id: 'mock-alert-12',
    severity: 'Severe',
    event: 'Cold Wave',
    headline: 'ORANGE ALERT: Severe Cold Wave in Northern Dhule',
    description: 'Minimum temperatures are expected to drop below 4°C, potentially causing ground frost.',
    instruction: 'Protect livestock from cold. Light bonfires around orchards to prevent frost damage to crops.',
    status: 'ACTIVE',
    area: 'Dhule, Maharashtra',
    areaCode: 'MH-DH',
    version: 1,
    issuedAt: new Date(Date.now() - 172800000).toISOString(),
    expiresAt: new Date(Date.now() + 86400000).toISOString()
  }
];
