-- Assumes shared public.users(id) and public.locations(id, user_id) exist.
create extension if not exists pgcrypto;
create table public.farmer_profiles (id uuid primary key default gen_random_uuid(), user_id uuid not null unique references public.users(id) on delete cascade, preferred_language text not null default 'en', primary_location_id uuid references public.locations(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.crops (id uuid primary key default gen_random_uuid(), name text not null unique, scientific_name text, season text, default_growth_days integer check(default_growth_days>0), is_active boolean not null default true, created_at timestamptz not null default now());
create table public.farmer_crops (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, crop_id uuid not null references public.crops(id) on delete restrict, location_id uuid not null references public.locations(id) on delete cascade, sowing_date date, current_growth_stage text, is_primary boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.weather_snapshots (id uuid primary key default gen_random_uuid(), location_id uuid not null references public.locations(id) on delete cascade, forecast_date date not null, fetched_at timestamptz not null default now(), expires_at timestamptz not null, provider text not null default 'open-meteo', latitude numeric(9,6) not null, longitude numeric(9,6) not null, current_conditions jsonb not null default '{}'::jsonb, daily_forecast jsonb not null default '{}'::jsonb, unique(location_id,forecast_date));
create table public.advisories (id uuid primary key default gen_random_uuid(), farmer_crop_id uuid not null references public.farmer_crops(id) on delete cascade, weather_snapshot_id uuid not null references public.weather_snapshots(id) on delete cascade, verdict text not null, reason text not null, recommended_action text not null, urgency text not null check(urgency in ('low','medium','high','critical')), rule_version text not null, evidence jsonb not null default '{}'::jsonb, generated_at timestamptz not null default now(), expires_at timestamptz not null);
create table public.market_prices (id uuid primary key default gen_random_uuid(), crop_id uuid not null references public.crops(id) on delete cascade, market_name text not null, district text, state text, price_date date not null, modal_price numeric(12,2) not null, min_price numeric(12,2), max_price numeric(12,2), unit text not null default 'INR/quintal', provider text not null default 'agmarknet', fetched_at timestamptz not null default now(), unique(crop_id,market_name,price_date));
alter table public.farmer_profiles enable row level security; alter table public.crops enable row level security; alter table public.farmer_crops enable row level security; alter table public.weather_snapshots enable row level security; alter table public.advisories enable row level security; alter table public.market_prices enable row level security;
create policy "own profile" on public.farmer_profiles for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "read crops" on public.crops for select to authenticated using(is_active=true);
create policy "own farmer crops" on public.farmer_crops for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own location weather" on public.weather_snapshots for select using(exists(select 1 from public.locations l where l.id=location_id and l.user_id=auth.uid()));
create policy "own crop advisories" on public.advisories for select using(exists(select 1 from public.farmer_crops fc where fc.id=farmer_crop_id and fc.user_id=auth.uid()));
create policy "read market prices" on public.market_prices for select to authenticated using(true);
