/**
 * Supabase Sync Unit Tests
 *
 * Tests the Supabase shared-data sync layer in isolation.
 * Uses in-memory mocks — no real Supabase connection required.
 *
 * Test coverage (maps to requirements 1–12):
 *   1.  New local alert is representable in Supabase (field mapping check)
 *   2.  Local alert.id maps correctly to Supabase external_id
 *   3.  Repeated sync calls upsert (not duplicate-insert) — idempotency
 *   4.  Alert update triggers an upsert with changed fields
 *   5.  Extreme severity is accepted without normalisation error
 *   6.  area and area_code are present in the synced payload
 *   7.  Status ACTIVE/EXPIRED/CANCELLED all pass through correctly
 *   8.  Supabase client unavailable → sync returns early, no error thrown
 *   9.  Supabase network error → sync logs and returns without throwing
 *   10. polygonToWkt converts JSON lat/lon pairs to PostGIS WKT correctly
 *   11. polygonToWkt handles null/invalid gracefully (returns null)
 *   12. _mapAlertToSupabase produces all expected fields
 *
 * NOT tested here (tested by existing test files):
 *   - Dashboard read path  (reliability.test.js)
 *   - MQTT / Web Push      (mqtt-webpush.test.js)
 *   - FAST/SLOW behaviour  (reliability.test.js)
 *   - Alert ingestion flow (reliability.test.js / processing.test.js)
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import {
  _mapAlertToSupabase,
  polygonToWkt,
  syncAlertToSupabase,
  syncAlertsToSupabase,
} from '../services/supabaseSync.js';

// ─── Minimal alert fixture ────────────────────────────────────────────────────

function makeAlert(overrides = {}) {
  return {
    id:           overrides.id          ?? 'imd-IMD-CAP-TEST-001',
    source:       overrides.source      ?? 'imd',
    sourceId:     overrides.sourceId    ?? 'IMD-CAP-TEST-001',
    event:        overrides.event       ?? 'Heavy Rainfall',
    headline:     overrides.headline    ?? 'Heavy Rainfall Warning',
    description:  overrides.description ?? 'Heavy rainfall expected in coastal districts.',
    severity:     overrides.severity    ?? 'Severe',
    status:       overrides.status      ?? 'ACTIVE',
    area:         overrides.area        ?? 'Dakshina Kannada, Karnataka',
    areaCode:     overrides.areaCode    ?? 'DAKSHINA KANNADA',
    latitude:     overrides.latitude    ?? 12.86,
    longitude:    overrides.longitude   ?? 74.84,
    polygon:      overrides.polygon     ?? null,
    language:     overrides.language    ?? 'en',
    effectiveAt:  overrides.effectiveAt ?? '2026-01-01T00:00:00Z',
    expiresAt:    overrides.expiresAt   ?? '2099-12-31T00:00:00Z',
    issuedAt:     overrides.issuedAt    ?? '2026-01-01T00:00:00Z',
    createdAt:    overrides.createdAt   ?? '2026-01-01T00:00:00Z',
    updatedAt:    overrides.updatedAt   ?? '2026-01-01T00:00:00Z',
    ...overrides,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Field mapping tests (_mapAlertToSupabase)
// ─────────────────────────────────────────────────────────────────────────────

describe('_mapAlertToSupabase — field mapping', () => {
  // Test 1: New local alert produces a valid Supabase payload
  it('maps a new local alert to a valid Supabase row payload', () => {
    const alert = makeAlert();
    const row   = _mapAlertToSupabase(alert);

    expect(row).not.toBeNull();
    expect(row.external_id).toBeDefined();
    expect(row.type).toBe('Heavy Rainfall');
    expect(row.title).toBe('Heavy Rainfall Warning');
    expect(row.severity).toBe('Severe');
    expect(row.status).toBe('ACTIVE');
    expect(row.source).toBe('imd');
    expect(row.language).toBe('en');
    expect(row.updated_at).toBeDefined();
  });

  // Test 2: Local alert.id maps to external_id
  it('maps local alert.id to Supabase external_id', () => {
    const alert = makeAlert({ id: 'imd-IMD-CAP-XYZ-999' });
    const row   = _mapAlertToSupabase(alert);

    expect(row.external_id).toBe('imd-IMD-CAP-XYZ-999');
    // Supabase UUID id is NOT present in the payload — it is generated by Postgres
    expect(row.id).toBeUndefined();
  });

  // Test 3: Payload is idempotent — mapping the same alert twice gives same external_id
  it('mapping the same alert twice produces the same external_id (idempotency)', () => {
    const alert = makeAlert();
    const row1  = _mapAlertToSupabase(alert);
    const row2  = _mapAlertToSupabase(alert);

    expect(row1.external_id).toBe(row2.external_id);
    // type, severity, status should be the same
    expect(row1.type).toBe(row2.type);
    expect(row1.severity).toBe(row2.severity);
  });

  // Test 4: Updated alert fields are reflected in the payload
  it('maps updated alert fields correctly', () => {
    const original = makeAlert({ severity: 'Moderate', status: 'ACTIVE' });
    const updated  = makeAlert({ severity: 'Extreme',  status: 'ACTIVE', description: 'Cyclonic storm approaching.' });

    const rowOriginal = _mapAlertToSupabase(original);
    const rowUpdated  = _mapAlertToSupabase(updated);

    expect(rowOriginal.severity).toBe('Moderate');
    expect(rowUpdated.severity).toBe('Extreme');
    expect(rowUpdated.description).toBe('Cyclonic storm approaching.');
  });

  // Test 5: Extreme severity passes through correctly
  it('accepts Extreme severity without normalisation error', () => {
    const alert = makeAlert({ severity: 'Extreme' });
    const row   = _mapAlertToSupabase(alert);

    expect(row.severity).toBe('Extreme');
  });

  // Test 6: area and area_code are present
  it('includes area and area_code in the synced payload', () => {
    const alert = makeAlert({
      area:     'Dakshina Kannada, Karnataka',
      areaCode: 'DAKSHINA KANNADA',
    });
    const row = _mapAlertToSupabase(alert);

    expect(row.area).toBe('Dakshina Kannada, Karnataka');
    expect(row.area_code).toBe('DAKSHINA KANNADA');
  });

  // Test 7: All valid statuses pass through
  it.each([['ACTIVE'], ['EXPIRED'], ['CANCELLED']])(
    'passes status %s through correctly',
    (status) => {
      const alert = makeAlert({ status });
      const row   = _mapAlertToSupabase(alert);
      expect(row.status).toBe(status);
    }
  );

  // Test 12: All expected Supabase columns are present
  it('produces all expected Supabase columns', () => {
    const alert = makeAlert();
    const row   = _mapAlertToSupabase(alert);

    const expectedKeys = [
      'external_id', 'type', 'title', 'description',
      'severity', 'status', 'source', 'source_id',
      'language', 'area', 'area_code',
      'latitude', 'longitude', 'region_geom',
      'valid_from', 'valid_to', 'issued_at',
      'created_at', 'updated_at',
    ];

    for (const key of expectedKeys) {
      expect(row, `missing key: ${key}`).toHaveProperty(key);
    }
  });

  // Test: handles missing alert gracefully
  it('returns null for a null alert', () => {
    expect(_mapAlertToSupabase(null)).toBeNull();
  });

  it('returns null for an alert missing id', () => {
    expect(_mapAlertToSupabase({ event: 'test' })).toBeNull();
  });

  // Test: handles repo-style snake_case aliases (from repository SELECT … AS)
  it('handles snake_case aliases from repository queries', () => {
    const repoAlert = {
      id:           'imd-REPO-001',
      source:       'imd',
      source_id:    'REPO-001',
      event:        'Cyclone Warning',
      severity:     'Extreme',
      status:       'ACTIVE',
      area:         'Chennai, Tamil Nadu',
      area_code:    'CHENNAI',
      latitude:     13.08,
      longitude:    80.27,
      language:     'en',
      effective_at: '2026-01-01T00:00:00Z',
      expires_at:   '2099-01-01T00:00:00Z',
      issued_at:    '2026-01-01T00:00:00Z',
      created_at:   '2026-01-01T00:00:00Z',
      updated_at:   '2026-01-01T00:00:00Z',
    };
    const row = _mapAlertToSupabase(repoAlert);
    expect(row.external_id).toBe('imd-REPO-001');
    expect(row.source_id).toBe('REPO-001');
    expect(row.severity).toBe('Extreme');
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Polygon WKT conversion
// ─────────────────────────────────────────────────────────────────────────────

describe('polygonToWkt — coordinate conversion', () => {
  // Test 10: Valid polygon JSON → WKT
  it('converts a valid JSON lat/lon polygon to PostGIS WKT', () => {
    const polygon = JSON.stringify([
      { lat: 12.0, lon: 74.0 },
      { lat: 13.0, lon: 74.0 },
      { lat: 13.0, lon: 75.0 },
      { lat: 12.0, lon: 75.0 },
    ]);
    const wkt = polygonToWkt(polygon);

    expect(wkt).not.toBeNull();
    expect(wkt).toMatch(/^POLYGON\(\(/);
    // Coordinates should be lon lat (PostGIS order)
    expect(wkt).toContain('74 12');
    expect(wkt).toContain('74 13');
    // Ring must be closed
    const inner = wkt.replace('POLYGON((', '').replace('))', '');
    const pairs = inner.split(', ');
    expect(pairs[0]).toBe(pairs[pairs.length - 1]);
  });

  // Test 11a: null polygon → null
  it('returns null for null polygon', () => {
    expect(polygonToWkt(null)).toBeNull();
  });

  // Test 11b: empty string → null
  it('returns null for empty string', () => {
    expect(polygonToWkt('')).toBeNull();
  });

  // Test 11c: invalid JSON → null
  it('returns null for invalid JSON', () => {
    expect(polygonToWkt('not-json')).toBeNull();
  });

  // Test 11d: fewer than 3 points → null (not a polygon)
  it('returns null for fewer than 3 coordinate pairs', () => {
    const tooFew = JSON.stringify([{ lat: 1, lon: 2 }, { lat: 3, lon: 4 }]);
    expect(polygonToWkt(tooFew)).toBeNull();
  });

  // Test 11e: non-numeric coordinates → null
  it('returns null when coordinates are non-numeric', () => {
    const bad = JSON.stringify([
      { lat: 'a', lon: 74 },
      { lat: 13, lon: 74 },
      { lat: 13, lon: 75 },
    ]);
    expect(polygonToWkt(bad)).toBeNull();
  });

  it('already-closed ring is not double-closed', () => {
    const polygon = JSON.stringify([
      { lat: 12.0, lon: 74.0 },
      { lat: 13.0, lon: 74.0 },
      { lat: 13.0, lon: 75.0 },
      { lat: 12.0, lon: 74.0 }, // already closed
    ]);
    const wkt = polygonToWkt(polygon);
    // Should still be valid and not have an extra pair
    expect(wkt).toMatch(/^POLYGON\(\(/);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// syncAlertToSupabase — client availability and error handling
// ─────────────────────────────────────────────────────────────────────────────

describe('syncAlertToSupabase — Supabase client handling', () => {
  let originalModule;

  beforeEach(async () => {
    // Import the client module so we can mock it
    originalModule = await import('../db/supabaseClient.js');
    vi.resetModules();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  // Test 8: Supabase client unavailable → returns early without throwing
  it('returns early when Supabase client is null (credentials not set)', async () => {
    // Mock getSupabaseClient to return null
    vi.doMock('../db/supabaseClient.js', () => ({
      getSupabaseClient: () => null,
    }));

    // Dynamic import after mock
    const { syncAlertToSupabase: syncFn } = await import('../services/supabaseSync.js');

    const alert = makeAlert();
    // Must not throw
    await expect(syncFn(alert, 'created')).resolves.toBeUndefined();
  });

  // Test 9a: Supabase upsert returns an error → logs but does not throw
  it('handles Supabase API error without throwing', async () => {
    const mockUpsert = vi.fn().mockResolvedValue({ error: { message: 'connection refused', code: '500' } });
    const mockFrom   = vi.fn().mockReturnValue({ upsert: mockUpsert });

    vi.doMock('../db/supabaseClient.js', () => ({
      getSupabaseClient: () => ({ from: mockFrom }),
    }));

    const { syncAlertToSupabase: syncFn } = await import('../services/supabaseSync.js');

    const alert = makeAlert();
    await expect(syncFn(alert, 'created')).resolves.toBeUndefined();
  });

  // Test 9b: Supabase client throws a network error → logs but does not throw
  it('handles network-level exception without throwing', async () => {
    const mockUpsert = vi.fn().mockRejectedValue(new Error('Network timeout'));
    const mockFrom   = vi.fn().mockReturnValue({ upsert: mockUpsert });

    vi.doMock('../db/supabaseClient.js', () => ({
      getSupabaseClient: () => ({ from: mockFrom }),
    }));

    const { syncAlertToSupabase: syncFn } = await import('../services/supabaseSync.js');

    const alert = makeAlert();
    await expect(syncFn(alert, 'created')).resolves.toBeUndefined();
  });

  // Test 3 (runtime): Repeated sync does not call insert twice — uses upsert with onConflict
  it('calls upsert with onConflict=external_id for idempotency', async () => {
    const mockUpsert = vi.fn().mockResolvedValue({ error: null });
    const mockFrom   = vi.fn().mockReturnValue({ upsert: mockUpsert });

    vi.doMock('../db/supabaseClient.js', () => ({
      getSupabaseClient: () => ({ from: mockFrom }),
    }));

    const { syncAlertToSupabase: syncFn } = await import('../services/supabaseSync.js');

    const alert = makeAlert();
    await syncFn(alert, 'created');
    await syncFn(alert, 'created'); // second call simulates repeated sync

    expect(mockUpsert).toHaveBeenCalledTimes(2);
    // Both calls must use onConflict: 'external_id'
    for (const call of mockUpsert.mock.calls) {
      expect(call[1]).toEqual({ onConflict: 'external_id' });
    }
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// syncAlertsToSupabase — batch handling
// ─────────────────────────────────────────────────────────────────────────────

describe('syncAlertsToSupabase — batch sync', () => {
  it('maps multiple alerts to valid Supabase payloads (batch mapping contract)', () => {
    // Verify the payload structure that syncAlertsToSupabase would upsert.
    // We test _mapAlertToSupabase directly since that is the core logic —
    // the batch function adds only the upsert call on top.
    const alerts = [
      makeAlert({ id: 'imd-A1', sourceId: 'A1' }),
      makeAlert({ id: 'imd-A2', sourceId: 'A2', severity: 'Extreme' }),
      makeAlert({ id: 'imd-A3', sourceId: 'A3', status: 'EXPIRED' }),
    ];

    const payloads = alerts.map(_mapAlertToSupabase);
    expect(payloads).toHaveLength(3);
    expect(payloads.every(Boolean)).toBe(true);

    // external_id values must be distinct and match local alert ids
    expect(payloads[0].external_id).toBe('imd-A1');
    expect(payloads[1].external_id).toBe('imd-A2');
    expect(payloads[2].external_id).toBe('imd-A3');

    // Extreme severity passes through
    expect(payloads[1].severity).toBe('Extreme');

    // EXPIRED status passes through
    expect(payloads[2].status).toBe('EXPIRED');

    // No Supabase UUID in the payload — Postgres generates it
    expect(payloads.every(p => p.id === undefined)).toBe(true);
  });

  it('each batch payload has external_id as the dedup key', () => {
    const alerts = [
      makeAlert({ id: 'imd-B1', severity: 'Extreme' }),
      makeAlert({ id: 'imd-B2', status: 'EXPIRED' }),
    ];
    const payloads = alerts.map(_mapAlertToSupabase);
    expect(payloads[0].external_id).toBe('imd-B1');
    expect(payloads[1].external_id).toBe('imd-B2');
  });

  it('syncAlertsToSupabase resolves for empty array without throwing', async () => {
    // Must not throw regardless of client availability
    await expect(syncAlertsToSupabase([], 'expired')).resolves.toBeUndefined();
  });

  it('syncAlertsToSupabase resolves for non-empty array without throwing (no client)', async () => {
    // When client is null (no credentials configured), must silently resolve
    const alerts = [makeAlert({ id: 'imd-C1' })];
    await expect(syncAlertsToSupabase(alerts, 'expired')).resolves.toBeUndefined();
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Isolation: sync does NOT touch dashboard/notification code paths
// ─────────────────────────────────────────────────────────────────────────────

describe('isolation — sync does not touch local pipeline', () => {
  it('supabaseSync.js does not import notificationRouter', async () => {
    // This test ensures no accidental coupling to the notification path.
    // We verify by checking the module's imports don't reference the router.
    const { readFileSync } = await import('fs');
    const { resolve, dirname } = await import('path');
    const { fileURLToPath } = await import('url');

    const __dirname = dirname(fileURLToPath(import.meta.url));
    const syncFile = resolve(__dirname, '../services/supabaseSync.js');
    const src = readFileSync(syncFile, 'utf-8');

    expect(src).not.toContain('notificationRouter');
    expect(src).not.toContain('mqttService');
    expect(src).not.toContain('webPush');
    expect(src).not.toContain('deliveryService');
  });

  it('supabaseSync.js does not import from db/connection (read path)', async () => {
    const { readFileSync } = await import('fs');
    const { resolve, dirname } = await import('path');
    const { fileURLToPath } = await import('url');

    const __dirname = dirname(fileURLToPath(import.meta.url));
    const syncFile = resolve(__dirname, '../services/supabaseSync.js');
    const src = readFileSync(syncFile, 'utf-8');

    // supabaseSync should not query the local DB — it only maps provided objects
    expect(src).not.toContain("from '../db/connection");
  });
});
